#!/bin/dash
#  _                   _        
# | |__   _____      _| |_ ___  
# | '_ \ / _ \ \ /\ / / __/ _ \ 
# | | | | (_) \ V  V /| || (_) |
# |_| |_|\___/ \_/\_/  \__\___/ 
# Profile for: dash
cd() {
  command cd "$@" || return
  if [ -f howto ]; then
    cat howto
  fi
}
