#!/bin/fish
#  _                   _        
# | |__   _____      _| |_ ___  
# | '_ \ / _ \ \ /\ / / __/ _ \ 
# | | | | (_) \ V  V /| || (_) |
# |_| |_|\___/ \_/\_/  \__\___/ 
# Profile for: fish

function on_directory_change --on-variable PWD
    if test -f "howto"
        cat howto
    end
end
