#!/bin/zsh
#  _                   _        
# | |__   _____      _| |_ ___  
# | '_ \ / _ \ \ /\ / / __/ _ \ 
# | | | | (_) \ V  V /| || (_) |
# |_| |_|\___/ \_/\_/  \__\___/ 
# Profile for: zsh

function chpwd() {
  if [ -f "howto" ]; then
    cat howto
  fi
}
